---
title: "GLASS report figures"
author: "Philippe Glaziou"
date: "`r Sys.Date()`"
output:
  html_fragment:
  # Don’t include a table of contents
  toc: no
# Set standard figure width to 12 inches
fig_width: 12
# Don’t write figure captions
fig_caption: FALSE
---


```{r setup, include=FALSE}
# Set options, load data, utility functions

knitr::opts_chunk$set(
  echo = FALSE,
  results = "asis",
  message = FALSE,
  warning = FALSE
)


library(data.table)
library(here)
library(ggplot2)
library(whomap)
library(gridExtra)

load(here('data/gfreq.rda'))
load(here('data/gprop.rda'))
load(here('data/gimp.rda'))


```


# GLASS report - Figures


## Fig 1. Volume of AMR data reported by countries in 2018 and 2019
```{r echo=FALSE, message=FALSE, warning=FALSE, results = "asis", dev = 'png', fig.width=16, fig_1, fig.alt="Number of reported data points (Thousand), 2018-2019"} 
out18a <- gfreq[year==2018, .(tota=sum(ast, na.rm=TRUE)), by=iso3]
out19a <- gfreq[year==2019, .(tota=sum(ast, na.rm=TRUE)), by=iso3]

out18b <- gprop[year==2018, .(totb=sum(ast, na.rm=TRUE)), by=iso3]
out19b <- gprop[year==2019, .(totb=sum(ast, na.rm=TRUE)), by=iso3]

out18 <- merge(out18a, out18b, by='iso3', all.x=T, all.y=T)
out19 <- merge(out19a, out19b, by='iso3', all.x=T, all.y=T)

out18[, tot := rowSums(cbind(tota, totb), na.rm=TRUE)/1000]
out19[, tot := rowSums(cbind(tota, totb), na.rm=TRUE)/1000]
out18[, var := cut(tot, breaks=c(0,1,10,50,100,+Inf))]
out19[, var := cut(tot, breaks=c(0,1,10,50,100,+Inf))]

p1 <- whomap(out18, map.title='Reported data points in 2018', legend.title = 'Reported data points\n(Thousand)')
p2 <- whomap(out19, map.title='Reported data points in 2019', legend.title = 'Reported data points\n(Thousand)')

mp <- grid.arrange(p1, p2, ncol=2)

```
Note: the number of country data points is defined as the aggregated number of reported results for the year over all  specimen-pathogen-antibiotic combinations.




## Fig 2. Resistance prevalence over time, by sample type and pathogen
```{r echo=FALSE, message=FALSE, warning=FALSE, results = "asis", dev = 'png', fig.width=16, fig_1, fig.alt="Number of reported data points (Thousand), 2018-2019"} 
gfreq[, p.res := res/ast]
glass <-
  merge(gfreq[, .(
    iso3,
    year,
    specimen,
    pathogen,
    antibiotic,
    antibiotic.label2,
    origin,
    n = numsampledpatients,
    tot,
    p.res
  )], gprop[, .(iso3,
                year,
                specimen,
                pathogen,
                antibiotic,
                path.label,
                antibiotic.label,
                tot,
                p.res)],
  by = c("iso3", "year", "specimen", "pathogen", "antibiotic","tot","p.res"), all=T)



spec <- 'BLOOD'
path <- 'ESCCOL'
ab <- 'J01DD'
ylo <- 2015
yhi <- 2019
sel <- glass$specimen==spec & glass$pathogen==path & glass$antibiotic==ab & glass$year>=ylo
nobs <- sum(sel)
fit <- loess(p.res ~ year, data=glass[sel])
out <- data.table(year=ylo:yhi, iso3='', yhat=predict(fit, newdata=data.table(year=ylo:yhi)))

qplot(year, p.res, data=glass[sel], group=iso3, geom='line', colour=I('grey40'), 
            main='BSI caused by E. coli resistant to 3rd generation cephalosporins ') +
  geom_point(size=I(.5), colour=I('grey40')) +
  geom_line(aes(year, yhat), data=out, size=I(2)) +
  scale_y_continuous(name='Resistance (%)') +
  scale_x_continuous(breaks=ylo:yhi) +
  xlab('') +
  theme_bw(base_size = 18)




```





